### ISSUE TITLE
npm install version out of date

### ISSUE THREAD

**Issue by ukmoose** [dalhundal/sky-plus-hd#13]
Installing via "npm install sky-plus-hd" installs out of date version.  

So for example it doesn't include check to see if endpoint is a "Sky" box.

**Comment by dalhundal** [comment]
Thanks - very sloppy of me :-s
Will rectify asap

**Comment by ukmoose** [comment]
Just tried again.  If I install via npm package.json includes:
 "name": "sky-plus-hd",
  "version": "0.0.4",

where as package.json on github master 
 "name": "sky-plus-hd",
  "version": "0.1.1",

am I doing something wrong?

**Comment by dalhundal** [comment]
Nope, you're not doing anything wrong - it's not been updated. Reason being, I'm trashing the current version, working towards a decent v1. If you want to use this, I'd recommend getting the code from git instead, and checking out the v1-dev branch.

**Comment by ukmoose** [comment]
thanks I've started to cobble together a node-red (http://nodered.org) wrapper.

**Comment by dalhundal** [comment]
Cool - need to find time to get v1 out - knowing there's people using it is motivating :-). Give me a shout if I can help.
