### ISSUE TITLE
How can I run this?

### ISSUE THREAD

**Issue by leecollings** [dalhundal/sky-plus-hd#14]
Can someone give some advice as to how I can run the commands found in the cli file?

I want to create a script file that will reference the relevant file from this plugin, and then send a command to Pause my sky box.

The script will be put into my Domoticz system, but as there's no documentation.. I have no idea what to do, and I've never used node.js before. But I believe I just need to create one file, reference a file inside it, and then call the action I want.

Can anyone help?

**Comment by dalhundal** [comment]
Hi - happy to help you out if I can. Currently rewriting the app, though should be able to get you running something. Going to close this, as it's not strictly an issue - chat to you over at https://gitter.im/dalhundal/sky-plus-hd ? Let me know what OS you're running on.
