### ISSUE TITLE
Contact for implementation

### ISSUE THREAD

**Issue by sijones** [dalhundal/sky-plus-hd#16]
Hi Dal, Very sorry for using this method to contact you but I couldn't find another way of reaching you!

I am wanting to implement support of Sky in to Domoticz (open source home automation), am trying to understand what you are sending over the port, i.e. is it ascii numbers or hex etc - javascript isn't my strong point.

If you wouldn't mind sharing a little knowledge on the protocol to me so i can implement it would be appreciated!

Simon - sijones2010 at gmail.com

**Comment by dalhundal** [comment]
Added contact info in the readme.
Will email you with info
